version: '3'

networks:
  ya_net:
    driver: bridge

services:
  pg:
    build:
      context: .
      dockerfile: Dockerfile-pg
    networks:
      - ya_net
    ports:
      - "5832:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  fapi:
    build:
      context: .
      dockerfile: Dockerfile-fapi
    depends_on:
      pg:
        condition: service_healthy
    networks:
      - ya_net
    ports:
      - "8000:8000"
    environment:
      - DATABASE_DSN=postgresql+asyncpg://me:1111111@pg:5432/my
    restart: always
